### ISSUE TITLE
Data for Staff Size over time?

### ISSUE THREAD

**Issue by dHutchings** [pioneers/website#65]
Hey!

That graph of our impact (Schools, Teams, Mentors) looks really awesome.

Would you like to do that for PiE-Staff size too?  PiE-Staff are definitely affected by PiE, and I can dig up some numbers about staff size if you'd like.

Thanks!

**Comment by jiangdaniel** [comment]
Would you like us to create a separate graph for PiE staff or add it to our existing graph?

The PiE staff statistics are actually on the current PiE website (https://pioneers.berkeley.edu/about/); however, we decided to exclude them from the graph in order to simplify the graph, and because the number of PiE staff closely mirrored the number of mentors.

But I'm sure that we could discuss possibly adding the PiE staff statistics back to the graph if you'd like.

Thanks for your input!

**Comment by tobinsarah** [comment]
Probably makes sense to add it to the existing graph.

Also, would it be possible allow turning data sets "on" or "off"? For example, say you wanted to look at the number of schools in each season -- it would be nice to hide the mentor and student numbers and re-scale the graph to see the changes in team numbers over time more clearly.

**Comment by dHutchings** [comment]
Maybe we could combine "mentors" and "staff" into "college students"?  That would capture all classes of current undergrads who benefit from PiE, and not add another column to the chart.

**Comment by jiangdaniel** [comment]
Conversation continued on #280
