### ISSUE TITLE
Implement vendor prefixes for flexbox

### ISSUE THREAD

**Issue by tobinsarah** [pioneers/website#73]
It makes the page a lot longer and leaves a lot of unused white space. I think this issue is related to the listing of staff and sponsors, but I'll submit that separately.

![screen shot 2016-02-04 at 8 30 07 pm](https://cloud.githubusercontent.com/assets/3431933/12838107/4956f246-cb7e-11e5-9de9-72bb673e3780.png)

**Comment by tobinsarah** [comment]
Same as Issue #74, I see why its vertical now, but is there an easy way to compact things when viewing on a computer?

**Comment by cwang395** [comment]
What web browser are you using?

**Comment by tobinsarah** [comment]
It's fixed in Chrome, but not in Safari Version 6.2.3 (8537.85.12.18).

**Comment by cwang395** [comment]
Note: This is because Safari prior to version 6.1 only provide partial support of flexbox, which we used for the gallery and several other pages. According to [caniuse.com](http://caniuse.com/#search=flexbox), global usage of Safari prior to version 6.1 is less than 0.05%. In its non-prefixed form (the way we've used it), flex box is supported by 81.94% of all browsers. 

We can get it up to 95.89% by using vendor prefixes, for which there's a SCSS mixin somewhere in the project files...
